version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    restart: always

  transactions_api:
    build: .
    volumes:
      - ./app:/usr/src/app
    tty: true
    environment:
      DJANGO_SUPERUSER_ADMIN: admin
      DJANGO_SUPERUSER_EMAIL: admin
      DJANGO_SUPERUSER_PASSWORD: adminp2ss
      TESTDATA: 0
    command: ./start.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always